// This is a representative sample. A full list would be much larger.
// You can find comprehensive lists online, e.g., from npm packages like 'country-flag-emoji-json'
// or various public APIs.
export const countries = [
  { name: "United States", isoCode: "US", dial_code: "+1", flag: "🇺🇸" },
  { name: "United Kingdom", isoCode: "GB", dial_code: "+44", flag: "🇬🇧" },
  { name: "India", isoCode: "IN", dial_code: "+91", flag: "🇮🇳" },
  { name: "Germany", isoCode: "DE", dial_code: "+49", flag: "🇩🇪" },
  { name: "France", isoCode: "FR", dial_code: "+33", flag: "🇫🇷" },
  { name: "Japan", isoCode: "JP", dial_code: "+81", flag: "🇯🇵" },
  { name: "China", isoCode: "CN", dial_code: "+86", flag: "🇨🇳" },
  { name: "Australia", isoCode: "AU", dial_code: "+61", flag: "🇦🇺" },
  { name: "Brazil", isoCode: "BR", dial_code: "+55", flag: "🇧🇷" },
  { name: "Canada", isoCode: "CA", dial_code: "+1", flag: "🇨🇦" }, // Shares +1 with US
  { name: "Mexico", isoCode: "MX", dial_code: "+52", flag: "🇲🇽" },
  { name: "South Africa", isoCode: "ZA", dial_code: "+27", flag: "🇿🇦" },
  { name: "Argentina", isoCode: "AR", dial_code: "+54", flag: "🇦🇷" },
  { name: "Egypt", isoCode: "EG", dial_code: "+20", flag: "🇪🇬" },
  { name: "Nigeria", isoCode: "NG", dial_code: "+234", flag: "🇳🇬" },
  { name: "Russia", isoCode: "RU", dial_code: "+7", flag: "🇷🇺" }, // Shares +7 with Kazakhstan
  { name: "South Korea", isoCode: "KR", dial_code: "+82", flag: "🇰🇷" },
  { name: "Spain", isoCode: "ES", dial_code: "+34", flag: "🇪🇸" },
  { name: "Italy", isoCode: "IT", dial_code: "+39", flag: "🇮🇹" },
  { name: "Netherlands", isoCode: "NL", dial_code: "+31", flag: "🇳🇱" },
  { name: "Sweden", isoCode: "SE", dial_code: "+46", flag: "🇸🇪" },
  { name: "Norway", isoCode: "NO", dial_code: "+47", flag: "🇳🇴" },
  { name: "Denmark", isoCode: "DK", dial_code: "+45", flag: "🇩🇰" },
  { name: "Finland", isoCode: "FI", dial_code: "+358", flag: "🇫🇮" },
  { name: "Switzerland", isoCode: "CH", dial_code: "+41", flag: "🇨🇭" },
  { name: "Belgium", isoCode: "BE", dial_code: "+32", flag: "🇧🇪" },
  { name: "Austria", isoCode: "AT", dial_code: "+43", flag: "🇦🇹" },
  { name: "Portugal", isoCode: "PT", dial_code: "+351", flag: "🇵🇹" },
  { name: "Greece", isoCode: "GR", dial_code: "+30", flag: "🇬🇷" },
  { name: "Turkey", isoCode: "TR", dial_code: "+90", flag: "🇹🇷" },
  { name: "Saudi Arabia", isoCode: "SA", dial_code: "+966", flag: "🇸🇦" },
  { name: "United Arab Emirates", isoCode: "AE", dial_code: "+971", flag: "🇦🇪" },
  { name: "Singapore", isoCode: "SG", dial_code: "+65", flag: "🇸🇬" },
  { name: "Malaysia", isoCode: "MY", dial_code: "+60", flag: "🇲🇾" },
  { name: "Indonesia", isoCode: "ID", dial_code: "+62", flag: "🇮🇩" },
  { name: "Thailand", isoCode: "TH", dial_code: "+66", flag: "🇹🇭" },
  { name: "Vietnam", isoCode: "VN", dial_code: "+84", flag: "🇻🇳" },
  { name: "Philippines", isoCode: "PH", dial_code: "+63", flag: "🇵🇭" },
  { name: "New Zealand", isoCode: "NZ", dial_code: "+64", flag: "🇳🇿" },
  { name: "Ireland", isoCode: "IE", dial_code: "+353", flag: "🇮🇪" },
  { name: "Israel", isoCode: "IL", dial_code: "+972", flag: "🇮🇱" },
  { name: "Pakistan", isoCode: "PK", dial_code: "+92", flag: "🇵🇰" },
  { name: "Bangladesh", isoCode: "BD", dial_code: "+880", flag: "🇧🇩" },
  { name: "Colombia", isoCode: "CO", dial_code: "+57", flag: "🇨🇴" },
  { name: "Peru", isoCode: "PE", dial_code: "+51", flag: "🇵🇪" },
  { name: "Chile", isoCode: "CL", dial_code: "+56", flag: "🇨🇱" },
  { name: "Venezuela", isoCode: "VE", dial_code: "+58", flag: "🇻🇪" },
  { name: "Kenya", isoCode: "KE", dial_code: "+254", flag: "🇰🇪" },
  { name: "Ghana", isoCode: "GH", dial_code: "+233", flag: "🇬🇭" },
  { name: "Morocco", isoCode: "MA", dial_code: "+212", flag: "🇲🇦" },
  { name: "Tunisia", isoCode: "TN", dial_code: "+216", flag: "🇹🇳" },
  { name: "Ukraine", isoCode: "UA", dial_code: "+380", flag: "🇺🇦" },
  { name: "Poland", isoCode: "PL", dial_code: "+48", flag: "🇵🇱" },
  { name: "Czech Republic", isoCode: "CZ", dial_code: "+420", flag: "🇨🇿" },
  { name: "Hungary", isoCode: "HU", dial_code: "+36", flag: "🇭🇺" },
  { name: "Romania", isoCode: "RO", dial_code: "+40", flag: "🇷🇴" },
  { name: "Bulgaria", isoCode: "BG", dial_code: "+359", flag: "🇧🇬" },
  { name: "Croatia", isoCode: "HR", dial_code: "+385", flag: "🇭🇷" },
  { name: "Serbia", isoCode: "RS", dial_code: "+381", flag: "🇷🇸" },
  { name: "Bosnia and Herzegovina", isoCode: "BA", dial_code: "+387", flag: "🇧🇦" },
  { name: "Slovenia", isoCode: "SI", dial_code: "+386", flag: "🇸🇮" },
  { name: "Slovakia", isoCode: "SK", dial_code: "+421", flag: "🇸🇰" },
  { name: "Lithuania", isoCode: "LT", dial_code: "+370", flag: "🇱🇹" },
  { name: "Latvia", isoCode: "LV", dial_code: "+371", flag: "🇱🇻" },
  { name: "Estonia", isoCode: "EE", dial_code: "+372", flag: "🇪🇪" },
  { name: "Belarus", isoCode: "BY", dial_code: "+375", flag: "🇧🇾" },
  { name: "Moldova", isoCode: "MD", dial_code: "+373", flag: "🇲🇩" },
  { name: "Kazakhstan", isoCode: "KZ", dial_code: "+7", flag: "🇰🇿" }, // Shares +7 with Russia
  { name: "Uzbekistan", isoCode: "UZ", dial_code: "+998", flag: "🇺🇿" },
  { name: "Azerbaijan", isoCode: "AZ", dial_code: "+994", flag: "🇦🇿" },
  { name: "Georgia", isoCode: "GE", dial_code: "+995", flag: "🇬🇪" },
  { name: "Armenia", isoCode: "AM", dial_code: "+374", flag: "🇦🇲" },
  { name: "Afghanistan", isoCode: "AF", dial_code: "+93", flag: "🇦🇫" },
  { name: "Iran", isoCode: "IR", dial_code: "+98", flag: "🇮🇷" },
  { name: "Iraq", isoCode: "IQ", dial_code: "+964", flag: "🇮🇶" },
  { name: "Syria", isoCode: "SY", dial_code: "+963", flag: "🇸🇾" },
  { name: "Lebanon", isoCode: "LB", dial_code: "+961", flag: "🇱🇧" },
  { name: "Jordan", isoCode: "JO", dial_code: "+962", flag: "🇯🇴" },
  { name: "Kuwait", isoCode: "KW", dial_code: "+965", flag: "🇰🇼" },
  { name: "Qatar", isoCode: "QA", dial_code: "+974", flag: "🇶🇦" },
  { name: "Bahrain", isoCode: "BH", dial_code: "+973", flag: "🇧🇭" },
  { name: "Oman", isoCode: "OM", dial_code: "+968", flag: "🇴🇲" },
  { name: "Yemen", isoCode: "YE", dial_code: "+967", flag: "🇾🇪" },
  { name: "Cyprus", isoCode: "CY", dial_code: "+357", flag: "🇨🇾" },
  { name: "Malta", isoCode: "MT", dial_code: "+356", flag: "🇲🇹" },
  { name: "Iceland", isoCode: "IS", dial_code: "+354", flag: "🇮🇸" },
  { name: "Greenland", isoCode: "GL", dial_code: "+299", flag: "🇬🇱" },
  { name: "Fiji", isoCode: "FJ", dial_code: "+679", flag: "🇫🇯" },
  { name: "Papua New Guinea", isoCode: "PG", dial_code: "+675", flag: "🇵🇬" },
  { name: "Solomon Islands", isoCode: "SB", dial_code: "+677", flag: "🇸🇧" },
  { name: "Vanuatu", isoCode: "VU", dial_code: "+678", flag: "🇻🇺" },
  { name: "Samoa", isoCode: "WS", dial_code: "+685", flag: "🇼🇸" },
  { name: "Tonga", isoCode: "TO", dial_code: "+676", flag: "🇹🇴" },
  { name: "Kiribati", isoCode: "KI", dial_code: "+686", flag: "🇰🇮" },
  { name: "Tuvalu", isoCode: "TV", dial_code: "+688", flag: "🇹🇻" },
  { name: "Nauru", isoCode: "NR", dial_code: "+674", flag: "🇳🇷" },
  { name: "Palau", isoCode: "PW", dial_code: "+680", flag: "🇵🇼" },
  { name: "Marshall Islands", isoCode: "MH", dial_code: "+692", flag: "🇲🇭" },
  { name: "Micronesia", isoCode: "FM", dial_code: "+691", flag: "🇫🇲" },
  { name: "Timor-Leste", isoCode: "TL", dial_code: "+670", flag: "🇹🇱" },
  { name: "Brunei", isoCode: "BN", dial_code: "+673", flag: "🇧🇳" },
  { name: "Cambodia", isoCode: "KH", dial_code: "+855", flag: "🇰🇭" },
  { name: "Laos", isoCode: "LA", dial_code: "+856", flag: "🇱🇦" },
  { name: "Myanmar", isoCode: "MM", dial_code: "+95", flag: "🇲🇲" },
  { name: "Sri Lanka", isoCode: "LK", dial_code: "+94", flag: "🇱🇰" },
  { name: "Maldives", isoCode: "MV", dial_code: "+960", flag: "🇲🇻" },
  { name: "Nepal", isoCode: "NP", dial_code: "+977", flag: "🇳🇵" },
  { name: "Bhutan", isoCode: "BT", dial_code: "+975", flag: "🇧🇹" },
  { name: "Mongolia", isoCode: "MN", dial_code: "+976", flag: "🇲🇳" },
  { name: "North Korea", isoCode: "KP", dial_code: "+850", flag: "🇰🇵" },
  { name: "Cuba", isoCode: "CU", dial_code: "+53", flag: "🇨🇺" },
  { name: "Jamaica", isoCode: "JM", dial_code: "+1-876", flag: "🇯🇲" },
  { name: "Haiti", isoCode: "HT", dial_code: "+509", flag: "🇭🇹" },
  { name: "Dominican Republic", isoCode: "DO", dial_code: "+1-809", flag: "🇩🇴" },
  { name: "Puerto Rico", isoCode: "PR", dial_code: "+1-787", flag: "🇵🇷" },
  { name: "Trinidad and Tobago", isoCode: "TT", dial_code: "+1-868", flag: "🇹🇹" },
  { name: "Bahamas", isoCode: "BS", dial_code: "+1-242", flag: "🇧🇸" },
  { name: "Barbados", isoCode: "BB", dial_code: "+1-246", flag: "🇧🇧" },
  { name: "Saint Lucia", isoCode: "LC", dial_code: "+1-758", flag: "🇱🇨" },
  { name: "Grenada", isoCode: "GD", dial_code: "+1-473", flag: "🇬🇩" },
  { name: "Saint Vincent and the Grenadines", isoCode: "VC", dial_code: "+1-784", flag: "🇻🇨" },
  { name: "Antigua and Barbuda", isoCode: "AG", dial_code: "+1-268", flag: "🇦🇬" },
  { name: "Dominica", isoCode: "DM", dial_code: "+1-767", flag: "🇩🇲" },
  { name: "Saint Kitts and Nevis", isoCode: "KN", dial_code: "+1-869", flag: "🇰🇳" },
  { name: "Belize", isoCode: "BZ", dial_code: "+501", flag: "🇧🇿" },
  { name: "Guatemala", isoCode: "GT", dial_code: "+502", flag: "🇬🇹" },
  { name: "Honduras", isoCode: "HN", dial_code: "+504", flag: "🇭🇳" },
  { name: "El Salvador", isoCode: "SV", dial_code: "+503", flag: "🇸🇻" },
  { name: "Nicaragua", isoCode: "NI", dial_code: "+505", flag: "🇳🇮" },
  { name: "Costa Rica", isoCode: "CR", dial_code: "+506", flag: "🇨🇷" },
  { name: "Panama", isoCode: "PA", dial_code: "+507", flag: "🇵🇦" },
  { name: "Ecuador", isoCode: "EC", dial_code: "+593", flag: "🇪🇨" },
  { name: "Bolivia", isoCode: "BO", dial_code: "+591", flag: "🇧🇴" },
  { name: "Paraguay", isoCode: "PY", dial_code: "+595", flag: "🇵🇾" },
  { name: "Uruguay", isoCode: "UY", dial_code: "+598", flag: "🇺🇾" },
  { name: "Guyana", isoCode: "GY", dial_code: "+592", flag: "🇬🇾" },
  { name: "Suriname", isoCode: "SR", dial_code: "+597", flag: "🇸🇷" },
  { name: "French Guiana", isoCode: "GF", dial_code: "+594", flag: "🇬🇫" },
  { name: "Algeria", isoCode: "DZ", dial_code: "+213", flag: "🇩🇿" },
  { name: "Angola", isoCode: "AO", dial_code: "+244", flag: "🇦🇴" },
  { name: "Benin", isoCode: "BJ", dial_code: "+229", flag: "🇧🇯" },
  { name: "Botswana", isoCode: "BW", dial_code: "+267", flag: "🇧🇼" },
  { name: "Burkina Faso", isoCode: "BF", dial_code: "+226", flag: "🇧🇫" },
  { name: "Burundi", isoCode: "BI", dial_code: "+257", flag: "🇧🇮" },
  { name: "Cabo Verde", isoCode: "CV", dial_code: "+238", flag: "🇨🇻" },
  { name: "Cameroon", isoCode: "CM", dial_code: "+237", flag: "🇨🇲" },
  { name: "Central African Republic", isoCode: "CF", dial_code: "+236", flag: "🇨🇫" },
  { name: "Chad", isoCode: "TD", dial_code: "+235", flag: "🇹🇩" },
  { name: "Comoros", isoCode: "KM", dial_code: "+269", flag: "🇰🇲" },
  { name: "Congo (Brazzaville)", isoCode: "CG", dial_code: "+242", flag: "🇨🇬" },
  { name: "Congo (Kinshasa)", isoCode: "CD", dial_code: "+243", flag: "🇨🇩" },
  { name: "Côte d'Ivoire", isoCode: "CI", dial_code: "+225", flag: "🇨🇮" },
  { name: "Djibouti", isoCode: "DJ", dial_code: "+253", flag: "🇩🇯" },
  { name: "Equatorial Guinea", isoCode: "GQ", dial_code: "+240", flag: "🇬🇶" },
  { name: "Eritrea", isoCode: "ER", dial_code: "+291", flag: "🇪🇷" },
  { name: "Eswatini", isoCode: "SZ", dial_code: "+268", flag: "🇸🇿" },
  { name: "Ethiopia", isoCode: "ET", dial_code: "+251", flag: "🇪🇹" },
  { name: "Gabon", isoCode: "GA", dial_code: "+241", flag: "🇬🇦" },
  { name: "Gambia", isoCode: "GM", dial_code: "+220", flag: "🇬🇲" },
  { name: "Guinea", isoCode: "GN", dial_code: "+224", flag: "🇬🇳" },
  { name: "Guinea-Bissau", isoCode: "GW", dial_code: "+245", flag: "🇬🇼" },
  { name: "Lesotho", isoCode: "LS", dial_code: "+266", flag: "🇱🇸" },
  { name: "Liberia", isoCode: "LR", dial_code: "+231", flag: "🇱🇷" },
  { name: "Libya", isoCode: "LY", dial_code: "+218", flag: "🇱🇾" },
  { name: "Madagascar", isoCode: "MG", dial_code: "+261", flag: "🇲🇬" },
  { name: "Malawi", isoCode: "MW", dial_code: "+265", flag: "🇲🇼" },
  { name: "Mali", isoCode: "ML", dial_code: "+223", flag: "🇲🇱" },
  { name: "Mauritania", isoCode: "MR", dial_code: "+222", flag: "🇲🇷" },
  { name: "Mauritius", isoCode: "MU", dial_code: "+230", flag: "🇲🇺" },
  { name: "Mozambique", isoCode: "MZ", dial_code: "+258", flag: "🇲🇿" },
  { name: "Namibia", isoCode: "NA", dial_code: "+264", flag: "🇳🇦" },
  { name: "Niger", isoCode: "NE", dial_code: "+227", flag: "🇳🇪" },
  { name: "Rwanda", isoCode: "RW", dial_code: "+250", flag: "🇷🇼" },
  { name: "Sao Tome and Principe", isoCode: "ST", dial_code: "+239", flag: "🇸🇹" },
  { name: "Senegal", isoCode: "SN", dial_code: "+221", flag: "🇸🇳" },
  { name: "Seychelles", isoCode: "SC", dial_code: "+248", flag: "🇸🇨" },
  { name: "Sierra Leone", isoCode: "SL", dial_code: "+232", flag: "🇸🇱" },
  { name: "Somalia", isoCode: "SO", dial_code: "+252", flag: "🇸🇴" },
  { name: "South Sudan", isoCode: "SS", dial_code: "+211", flag: "🇸🇸" },
  { name: "Sudan", isoCode: "SD", dial_code: "+249", flag: "🇸🇩" },
  { name: "Tanzania", isoCode: "TZ", dial_code: "+255", flag: "🇹🇿" },
  { name: "Togo", isoCode: "TG", dial_code: "+228", flag: "🇹🇬" },
  { name: "Uganda", isoCode: "UG", dial_code: "+256", flag: "🇺🇬" },
  { name: "Zambia", isoCode: "ZM", dial_code: "+260", flag: "🇿🇲" },
  { name: "Zimbabwe", isoCode: "ZW", dial_code: "+263", flag: "🇿🇼" },
]
